"use client";
import { useEffect,useState } from "react";
import { supabase } from "@/lib/supabase";
const ADMIN_EMAIL="milagroslove.1693@gmail.com";
type Order={id:string;user_id:string;status:string;total:number;payment_method:string|null;created_at:string;delivery_email:string|null;delivery_password:string|null;delivery_link:string|null;delivery_notes:string|null};
type Delivery={email:string;password:string;link:string;notes:string};
export default function AdminPage(){
 const[orders,setOrders]=useState<Order[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[forms,setForms]=useState<Record<string,Delivery>>({});
 const load=async()=>{if(!supabase){setError("Supabase no está configurado.");setLoading(false);return;}const{data:s}=await supabase.auth.getSession();const user=s.session?.user;if(!user){window.location.replace("/login?next=%2Fadmin");return;}if((user.email||"").toLowerCase()!==ADMIN_EMAIL){window.location.replace("/catalogo");return;}const{data,error}=await supabase.from("orders").select("id,user_id,status,total,payment_method,created_at,delivery_email,delivery_password,delivery_link,delivery_notes").order("created_at",{ascending:false});if(error)setError(`${error.code||"Error"}: ${error.message}`);else{const rows=(data||[]) as Order[];setOrders(rows);const next:Record<string,Delivery>={};rows.forEach(o=>next[o.id]={email:o.delivery_email||"",password:o.delivery_password||"",link:o.delivery_link||"",notes:o.delivery_notes||""});setForms(next);}setLoading(false);};
 useEffect(()=>{load();},[]);
 const changeStatus=async(id:string,status:string)=>{if(!supabase)return;setError("");const{error}=await supabase.from("orders").update({status}).eq("id",id);if(error){setError(`${error.code||"Error"}: ${error.message}`);return;}await load();};
 const setField=(id:string,key:keyof Delivery,value:string)=>setForms(p=>({...p,[id]:{...(p[id]||{email:"",password:"",link:"",notes:""}),[key]:value}}));
 const deliver=async(id:string)=>{if(!supabase)return;const f=forms[id]||{email:"",password:"",link:"",notes:""};setError("");const{error}=await supabase.from("orders").update({delivery_email:f.email||null,delivery_password:f.password||null,delivery_link:f.link||null,delivery_notes:f.notes||null,status:"delivered"}).eq("id",id);if(error){setError(`${error.code||"Error"}: ${error.message}`);return;}await load();};
 return <main className="mx-auto min-h-[75vh] max-w-5xl px-4 py-14"><p className="text-sm font-bold uppercase tracking-wider text-[#e3b64f]">Administración</p><h1 className="mt-2 text-4xl font-black">Pedidos</h1><p className="mt-3 text-white/50">Verifica el voucher y entrega los datos de acceso desde aquí.</p>{loading&&<p className="mt-10 text-white/50">Cargando pedidos...</p>}{error&&<p className="mt-6 rounded-xl border border-red-400/20 bg-red-400/10 p-4 text-red-200">{error}</p>}<div className="mt-8 space-y-5">{orders.map(o=>{const f=forms[o.id]||{email:"",password:"",link:"",notes:""};return <article key={o.id} className="rounded-3xl border border-white/10 bg-white/[0.04] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-sm text-[#e3b64f]">{o.id.slice(0,8).toUpperCase()}</p><p className="mt-1 text-xs text-white/40">{new Date(o.created_at).toLocaleString("es-PE")}</p></div><p className="text-xl font-black">S/ {Number(o.total).toFixed(2)}</p></div><p className="mt-4 text-sm">Estado: <b>{o.status}</b></p><p className="mt-1 text-xs text-white/40">Método: {o.payment_method?.toUpperCase()||"—"}</p><div className="mt-5 grid gap-2 sm:grid-cols-2"><button onClick={()=>changeStatus(o.id,"paid")} className="rounded-xl bg-emerald-500 px-4 py-3 font-black text-white">Confirmar pago</button><button onClick={()=>changeStatus(o.id,"processing")} className="rounded-xl bg-amber-400 px-4 py-3 font-black text-black">Procesando</button></div><div className="mt-6 border-t border-white/10 pt-5"><h2 className="font-black text-[#e3b64f]">Entrega al cliente</h2><div className="mt-4 grid gap-3"><input value={f.email} onChange={e=>setField(o.id,"email",e.target.value)} placeholder="Correo o usuario" className="rounded-xl border border-white/10 bg-black/30 px-4 py-3 outline-none"/><input value={f.password} onChange={e=>setField(o.id,"password",e.target.value)} placeholder="Contraseña o código" className="rounded-xl border border-white/10 bg-black/30 px-4 py-3 outline-none"/><input value={f.link} onChange={e=>setField(o.id,"link",e.target.value)} placeholder="Enlace de acceso (opcional)" className="rounded-xl border border-white/10 bg-black/30 px-4 py-3 outline-none"/><textarea value={f.notes} onChange={e=>setField(o.id,"notes",e.target.value)} placeholder="Instrucciones para el cliente" rows={3} className="rounded-xl border border-white/10 bg-black/30 px-4 py-3 outline-none"/><button onClick={()=>deliver(o.id)} className="rounded-xl bg-[#e3b64f] px-4 py-3 font-black text-black">Guardar y entregar producto</button></div></div></article>})}</div></main>;
}