"use client";

import Link from "next/link";
import { LogOut, MessageCircle, ShoppingCart, User } from "lucide-react";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { useCart } from "./CartProvider";
import { supabase } from "@/lib/supabase";

const ADMIN_EMAIL="milagroslove.1693@gmail.com";
function RomilLogo() { return <img src="/logo-romil-plus.png" alt="Romil Plus" className="h-[72px] w-[72px] shrink-0 object-contain sm:h-[82px] sm:w-[82px] lg:h-[92px] lg:w-[92px]"/>; }

export function Header() {
  const pathname = usePathname(); const router = useRouter(); const { items } = useCart();
  const [email,setEmail]=useState<string|null>(null); const [checkingSession,setCheckingSession]=useState(true);
  useEffect(()=>{if(!supabase){setCheckingSession(false);return;}supabase.auth.getSession().then(({data})=>{setEmail(data.session?.user.email??null);setCheckingSession(false);});const{data:authListener}=supabase.auth.onAuthStateChange((_event,session)=>{setEmail(session?.user.email??null);setCheckingSession(false);});return()=>authListener.subscription.unsubscribe();},[]);
  if(pathname==="/")return null; const hasItems=items.length>0; const isAdmin=(email||"").toLowerCase()===ADMIN_EMAIL; const supportHref=isAdmin?"/admin/soporte":"/soporte";
  const handleLogout=async()=>{if(!supabase)return;await supabase.auth.signOut();setEmail(null);router.push("/login");router.refresh();};
  return <header className="sticky top-0 z-50 border-b border-[#8f6927]/35 bg-[#020202]/95 backdrop-blur-xl"><div className="mx-auto flex w-full max-w-[1500px] items-center justify-between gap-5 px-4 py-3 sm:px-6 lg:px-10 lg:py-4 xl:px-12"><Link href="/" className="flex min-w-0 shrink-0 items-center gap-3 lg:gap-4"><RomilLogo/><span className="h-10 w-px bg-[#b78b37]/45 lg:h-12"/><span className="whitespace-nowrap text-[14px] font-extrabold tracking-[.08em] text-white sm:text-lg lg:text-xl">ROMIL <span className="text-[#e1b04a]">PLUS</span></span></Link><nav className="hidden flex-1 items-center justify-center gap-7 text-sm font-semibold text-[#c8c0b2] md:flex lg:gap-10 lg:text-[15px] xl:gap-12"><Link href="/catalogo" className="transition hover:text-[#e3b64f]">Catálogo</Link><Link href="/mis-compras" className="transition hover:text-[#e3b64f]">Mis compras</Link><Link href={supportHref} className="transition hover:text-[#e3b64f]">{isAdmin?"Mensajes":"Soporte"}</Link>{isAdmin&&<Link href="/admin" className="transition hover:text-[#e3b64f]">Pedidos</Link>}</nav><div className="ml-auto flex shrink-0 items-center gap-2 sm:gap-3">{!checkingSession&&email?<><Link href={supportHref} className="grid h-12 w-12 place-items-center rounded-xl border border-[#d5a536]/55 text-[#e1b04a] transition hover:bg-[#d5a536]/10 sm:h-14 sm:w-14 sm:rounded-2xl" aria-label={isAdmin?"Mensajes de clientes":"Atención al cliente"} title={isAdmin?"Mensajes de clientes":"Atención al cliente"}><MessageCircle size={21} strokeWidth={1.8}/></Link><Link href="/mis-compras" className="grid h-12 w-12 place-items-center rounded-xl border border-[#d5a536]/55 text-[#e1b04a] transition hover:bg-[#d5a536]/10 sm:h-14 sm:w-14 sm:rounded-2xl" aria-label={`Cuenta: ${email}`} title={email}><User size={21} strokeWidth={1.8}/></Link><button onClick={handleLogout} className="grid h-12 w-12 place-items-center rounded-xl border border-white/15 text-white/75 transition hover:border-red-400/50 hover:text-red-300 sm:h-14 sm:w-14 sm:rounded-2xl" aria-label="Cerrar sesión" title="Cerrar sesión"><LogOut size={20} strokeWidth={1.8}/></button></>:<Link href="/login" className="grid h-12 w-12 place-items-center rounded-xl border border-[#d5a536]/55 text-white transition hover:bg-[#d5a536]/10 sm:h-14 sm:w-14 sm:rounded-2xl" aria-label="Iniciar sesión"><User size={21} strokeWidth={1.8}/></Link>}<Link href="/carrito" className={`relative grid h-12 w-12 place-items-center rounded-xl border transition-all duration-200 sm:h-14 sm:w-14 sm:rounded-2xl ${hasItems?"border-[#d5a536]/70 bg-[#d5a536]/10 text-white shadow-[0_0_20px_rgba(213,165,54,.12)]":"border-[#d5a536]/55 text-white hover:bg-[#d5a536]/10"}`} aria-label="Carrito"><ShoppingCart size={21} strokeWidth={1.8}/>{hasItems&&<span className="absolute -right-1.5 -top-1.5 grid h-5 min-w-5 place-items-center rounded-full bg-[#d7b257] px-1 text-[11px] font-black text-black">{items.length}</span>}</Link></div></div></header>;
}
